apiVersion: v1
kind: Service
metadata:
  name: app-random
  namespace: default
spec:
  selector:
    app: app-random
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    type: LoadBalancer