apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "500m"      # Ограничение по CPU (0.5 ядра)
        memory: "256Mi"  # Ограничение по RAM (256MB)
      requests:
        cpu: "250m"      # Минимальный CPU (0.25 ядра)
        memory: "128Mi"  # Минимальный RAM (128MB)
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config