Vagrant.configure("2") do |config|
  # Первая виртуальная машина
  config.vm.define "nginx" do |app_nginx|
    app_nginx.vm.box = "bento/ubuntu-24.04"  # Укажите нужный образ
    app_nginx.vm.hostname = "vm1"            # Имя хоста
    app_nginx.vm.network "private_network", ip: "192.168.56.11"  # Сетевые настройки
    app_nginx.vm.network "forwarded_port", guest: 8080, host: 8080  # Проброс порта

    app_nginx.vm.provider "parallels" do |prl|
      prl.memory = "1024"  # Память для первой ВМ
      prl.cpus = 1         # CPU для первой ВМ
    end

    # Диск для первой ВМ с уникальным именем
    app_nginx.vm.disk :disk, name: "nginx_disk", size: "15GB", primary: true
    app_nginx.vm.provision "shell", path: "nginx_unzip.sh"  # Исправлено на app_nginx
  end

  # Вторая виртуальная машина
  config.vm.define "db" do |app_db|
    app_db.vm.box = "bento/ubuntu-24.04"  # Укажите нужный образ
    app_db.vm.hostname = "vm2"            # Имя хоста
    app_db.vm.network "private_network", ip: "192.168.56.10"  # Сетевые настройки

    app_db.vm.provider "parallels" do |prl|
      prl.memory = "1024"  # Память для второй ВМ
      prl.cpus = 1         # CPU для второй ВМ
    end

    # Диск для второй ВМ с уникальным именем
    app_db.vm.disk :disk, name: "db_disk", size: "15GB", primary: true
    app_db.vm.provision "shell", path: "mysql.sh"  # Исправлено на app_db
  end
end
