services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false  # Отключаем безопасность
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - efk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=""  # Отключаем пароль (если есть)
    ports:
      - "5601:5601"
    networks:
      - efk
    depends_on:
      - elasticsearch
    restart: always  # Автоматический перезапуск контейнера
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/status"]
      interval: 10s
      retries: 5

  fluentd:
    build:
      context: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - efk
    depends_on:
      - elasticsearch

  nodejs_app:
    build:
      context: .  # Указываем текущую директорию как контекст
    container_name: nodejs_app
    ports:
      - "10000:10000"
    networks:
      - efk
    depends_on:
      - fluentd

networks:
  efk:
    driver: bridge

volumes:
  es_data:
    driver: local
