version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_app
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always
