global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '8192858508:AAG5w7kHUn31_ayKakUaVKCFYplfdvcis8A'
        chat_id: -1002628255713
