- hosts: inst_jenks_master
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Java
      ansible.builtin.apt:
        name: openjdk-21-jdk
        state: present

    - name: Add Jenkins key
      ansible.builtin.get_url:
        url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
        dest: "/usr/share/keyrings/jenkins-keyring.asc"
        mode: '0644'

    - name: Add Jenkins repository
      ansible.builtin.copy:
        dest: "/etc/apt/sources.list.d/jenkins.list"
        content: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        mode: '0644'

    - name: Update apt cache after adding Jenkins repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Start Jenkins
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure Nginx directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/nginx/sites-available
        - /etc/nginx/sites-enabled

    - name: Configure Nginx for Jenkins
      ansible.builtin.template:
        src: template/nginx.conf.j2
        dest: /etc/nginx/sites-available/jenkins
      notify:
        - restart Nginx

    - name: Enable Jenkins site in Nginx
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/jenkins
        state: link
        src: /etc/nginx/sites-available/jenkins
      notify:
        - restart Nginx

    - name: Test Nginx configuration
      ansible.builtin.command:
        cmd: nginx -t
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Reload Nginx configuration
      ansible.builtin.command:
        cmd: nginx -s reload
      when: ansible_facts['distribution'] == 'Ubuntu'

  handlers:
    - name: restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted